shallow_clone: true
clone_folder: c:\projects\Voodoo-Mock

install:
  #patch so that the path to git and it's msys does'nt countains spaces...
  - ps: >-
      if($true)
      {
        $fso = New-Object -ComObject Scripting.FileSystemObject
        $env:PATH = $fso.getfolder("C:\Program Files (x86)\Git\cmd").ShortPath + ";" + $env:PATH
        $env:PATH = $fso.getfolder("C:\Program Files (x86)\Git\bin").ShortPath + ";" + $env:PATH
      }

  #needed to download other deps
  - cinst wget

  #let's install the LLVM distribution
  - cmd: mkdir LLVM_DOWNLOAD
  - cmd: cd LLVM_DOWNLOAD
  - cmd: wget "http://llvm.org/releases/3.6.0/LLVM-3.6.0-win32.exe"
  - cmd: 7z x LLVM-3.6.0-win32.exe
  - cmd: ren $_OUTDIR LLVM-3.6.0
  - cmd: move LLVM-3.6.0 c:\
  - ps: $env:PATH = 'c:\LLVM-3.6.0\bin;' + $env:PATH

  #let's try using mingw-w64
  - ps: cd "c:\"
  - cmd: wget "http://sourceforge.net/projects/mingw-w64/files/latest/download?source=typ_redirect" -O gcc-4.8-win32_4.8.5-20150504.7z
  - cmd: 7z x gcc-4.8-win32_4.8.5-20150504.7z
  - ps: $env:PATH = 'c:\gcc-4.8-win32\bin;c:\gcc-4.8-win32\i686-w64-mingw32\bin;' + $env:PATH

  #python modules
  - cmd: C:\Python27\scripts\pip install futures
  - cmd: C:\Python27\scripts\pip install clang==3.5
  - ps: $env:PATH = 'c:\Python27\Lib\site-packages;' + $env:PATH

build_script:
  
  # set env
  - cmd: set VOODOO_ROOT_DIR=c:\projects\Voodoo-Mock
#  - cmd: set PYTHONPATH=c:\projects\Voodoo-Mock\voodoo

  #build / test Voodoo-Mock
  - ps: cd "c:\projects\Voodoo-Mock"
  - cmd: make